---
title: "Load SQL Database"
author: "Jessica Mahone"
date: "`r Sys.Date()`"
output: html_document
---

```{r create database}

# Load packages
library(DBI)
library(RSQLite)

# Create and connect to db file
con <- dbConnect(RSQLite::SQLite(), "local_news_100_communities.db")

# Enable foreign key support
dbExecute(con, "PRAGMA foreign_keys = ON;")

```

```{r run schema}

# Read SQL file
sql_code <- paste(readLines("create_tables.sql"), collapse = "\n")

# Split by semicolon followed by newline (handles separate statements)
statements <- strsplit(sql_code, ";\\s*\\n")[[1]]

# Execute each statement
for (stmt in statements) {
  trimmed <- trimws(stmt)
  if (trimmed != "") dbExecute(con, paste0(trimmed, ";"))
}


```

```{r check work}

dbListTables(con)


```

```{r add data to tables}

dbWriteTable(con, "communities", communities_clean, append = TRUE)
dbWriteTable(con, "outlets", outlets_clean, append = TRUE)
dbWriteTable(con, "stories", stories_clean, append = TRUE)

```

```{r check work}


dbGetQuery(con, "SELECT COUNT(*) FROM communities;")
dbGetQuery(con, "SELECT COUNT(*) FROM outlets;")
dbGetQuery(con, "SELECT COUNT(*) FROM stories;")

```

